### ISSUE TITLE
Is there any guide how to use this plugin

### ISSUE THREAD

**Issue by hunter0x8** [nccgroup/CollaboratorPlusPlus#1]
Tried it in web security academy the burp collaborator is working but collaborator ++ not working can you provide any docs for this plugin

**Comment by C0DEbrained** [comment]
Hi Ahsan,
There's a bit of documentation in the about page of the plugin itself. 
Basically, this extension acts as a sort of proxy between Burp and the Collaborator server to collect the interactions for viewing in the table.

1. Setup the collaborator address and port in Collaborator++ (and if using a Collaborator++ server to enable authentication also ensure the secret is set correctly).
2. Start Collaborator++, if it connects successfully the tab color will turn green.
3. Trigger a collaborator event (e.g. using the Burp Collaborator tool to generate a URL and browsing to it or resolving the domain).
4. Collaborator++ should capture the interaction and log it to the table

Let me know if you have any other issues with this!
