### ISSUE TITLE
CollaboratorPlusPlus does not pick up Collaborator Everywhere Interactions

### ISSUE THREAD

**Issue by Greenwolf** [nccgroup/CollaboratorPlusPlus#2]
On the latest version of Burp + Collaborator Everywhere + CollaboratorPlusPlus, interactions are only picked up from Burp > Burp Collaborator Client, and not from the Collaborator Everywhere Extension.

This may be a combined flaw with Collaborator Everywhere in Burp 2.0, as it only reports into the Dashboard > Issue Activity, and not into the Target > Site Map > Issues Panel.

See how below when a Collaborator Everywhere generated payload is visited in another browser, it creates the issues in dashboard, but not in the site map or in the CollaboratorPlusPlus extension Interaction History.

Burp v2020.4.1 Professional

<img width="1271" alt="Screenshot 2020-06-11 at 17 58 47" src="https://user-images.githubusercontent.com/48361984/84418510-39a7b300-ac0f-11ea-99f6-30fe2b94eddd.png">

<img width="1272" alt="Screenshot 2020-06-11 at 17 59 28" src="https://user-images.githubusercontent.com/48361984/84418528-3f04fd80-ac0f-11ea-941f-2adf9273ea8f.png">

<img width="1262" alt="Screenshot 2020-06-11 at 18 15 29" src="https://user-images.githubusercontent.com/48361984/84419360-69a38600-ac10-11ea-90eb-0b4423a1c4a1.png">

<img width="1274" alt="Screenshot 2020-06-11 at 18 08 19" src="https://user-images.githubusercontent.com/48361984/84418550-46c4a200-ac0f-11ea-8673-95af6f827b5e.png">

**Comment by C0DEbrained** [comment]
Thanks for the useful screenshots!
From an initial guess, I imagine Collaborator Everywhere creates its collaborator instances immediately on loading and so will use the polling location set at that instant.

Collaborator++ functions by routing collaborator traffic through the extension (by setting 127.0.0.1:Collaborator++Port as polling location in project options) though the value is only set when the service is started.

Could you please try placing Collaborator Everywhere after Collaborator++ in the load order, and restarting Collaborator Everywhere once Collaborator++ is running?

**Comment by Greenwolf** [comment]
Hi @CoreyD97, yes changing the load order to put Collaborator++ first and then reloading Collaborator Everywhere works! Thank you very much for the advice 😃
